### PR TITLE
Add support for Stream construction from Iterators.

### PR DESCRIPTION
**Pull request by pvande**
As defined [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#iterator), the Iterator protocol is met by any object that implements a `next` method, with the expectation that such a function returns a hash of `{ value, done }` for each subsequent call.

This PR implements support for creating streams from such Iterators, and tests three independent implementations (including one from ES6, via Babel).

### CODE REVIEW

**Comment by pvande** [comment]
Related to #37.

**Comment by pvande** [comment]
It's also interesting to note that the internal `Iterator` model differs from the object returned from `Stream().iterator()` in that it _doesn't_ actually conform to the Iterator protocol.

I'd be happy to take a look at making that change as well (since it would remove the need for some of the noise like the `IteratorIterator` type), but I figured I'd send this out before I made any move to further disrupt the codebase.

**Comment by winterbe** [comment]
Thanks for your contribution. Looks good at first glance. I'll look into the details tomorrow. 

The reason that I've decided not to stick to the Iterator protocol for internal processing is memory consumption. I'm concerned that wrapping each object into an object hash `{value, done}` would unnecessarily pollute the heap when processing large amounts of data. 

Though the project is lacking any serious perf test so this is all blank theory.

**Comment by pvande** [comment]
I can definitely see how memory consumption would be a concern, but it does seem like a bit of a premature optimization from my perspective.  Let me see what I can draw up quickly as a performance test – the `IteratorIterator` from this PR should actually give us some useful data in that regard.

**Comment by pvande** [comment]
Here are the preliminary results from my experiments.

Tests were run 20 times with a 100,000,000 element (lazy) source.

Test case: [Direct Execution](https://gist.github.com/pvande/94b6beaaa575dd59c4e7#file-direct-js)
Timings:
- Min: 268
- Max: 303
- Avg: 280.85

Memory Profile: screen shot 2015-06-16 at 2 16 24 pm
Notes: This test was run to determine the lower bounds on time and memory requirements for the operations being performed.

Test case: [Stream.range](https://gist.github.com/pvande/94b6beaaa575dd59c4e7#file-range-js)
Timings:
- Min: 3258
- Max: 5301
- Avg: 4841.75

Memory Profile: screen shot 2015-06-16 at 2 33 33 pm
Notes: The slow steady growth is nothing to be particularly concerned about – it steps once per run of the test, which implies that the step up is just storing the run's statistics.

Test case: [Stream.range](https://gist.github.com/pvande/94b6beaaa575dd59c4e7#file-iterator-js)
Timings:
- Min: 3587
- Max: 5534
- Avg: 4759.1

Memory Profile: screen shot 2015-06-16 at 2 49 03 pm
Notes: Remarkably similar memory profile.  Overall not particularly surprising, considering we're discussing the creation of a single, short-lived object per-step; it's entirely possible that the JIT is optimizing the object away internally, since it's effectively being used as a tuple to pass two values to the `IteratorOp#advance` method.

Overall, I'd say that conforming to the Iterator protocol internally is likely to have less of a negative impact on either memory usage or performance than initially feared.

**Comment by winterbe** [comment]
Thanks for your effort. So it seems we're good to go to just stick with the iterator protocol. I'll create another issue for that.

**Comment by winterbe** [comment]
I've added the new constructor variant to the [APIDOC](https://github.com/winterbe/streamjs/blob/master/APIDOC.md#streamiterator).

**Pull request merged**
